Experiencing a serverError(500)?
Change debug mode to True in settings.py, deploy, and view error
if "improperly configured database" error, chances are you did not do one of the following before deploying:

settings.py should look as follows in the database section: (note the commented out sections).

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""

"""
#Use this when testing locally -- subsequent one is for Heroku
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cornellmake',
        'USER': 'justin',
        'PASSWORD': 'abc123',
        'HOST': 'localhost',
        'PORT': '',
    }
}
"""


# we only need the engine name, as heroku takes care of the rest
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Parse database configuration from $DATABASE_URL
DATABASES['default'] =  dj_database_url.config()

# Enable Persistent Connections
DATABASES['default']['CONN_MAX_AGE'] = 500

# Enable Connection Pooling (if desired)
#DATABASES['default']['ENGINE'] = 'django_postgrespool'
